### PR TITLE
finished quiz

### PR DESCRIPTION
**Pull request by tom-fitz**
Ready for review.

### CODE REVIEW

**Comment by morecallan** [comment]
@basictom - Looking awesome. _Definitely_ can see your design skillz here. My small comment is: make sure to actually fill in the link for your hrefs. My big comment is: duuuuuude, only one commit??

**Comment by tom-fitz** [comment]
@morecallan oh stop, you're gonna make me blush. I just added in actual links. I always forget to hit a stopping point and commit, probably should figure that out.

**Comment by tom-fitz** [comment]
@morecallan oh stop, you're gonna make me blush. I just pushed the requested changes. I never commit because I'm too focused on the task at hand, I should probably change that.

**Comment by morecallan** [comment]
👍 mergin'!

**Pull request merged**
